[package]
name = "rust_serde"
version = "0.1.0"
edition = "2024"
description = "A simple Rust library showing how to use Serde"
license = "MIT"

[dependencies]
serde ={ version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
